# GENERATED BY NifGram. DO NOT EDIT!
# ORIGINAL FILE: ./src/nifc/preasm/preasm_grammar.nif
import nifstreams

var
  IT*: TagId
  UT*: TagId
  FT*: TagId
  MT*: TagId
  BT*: TagId
  LoadT*: TagId
  CallT*: TagId
  VarargsT*: TagId
  VaddrT*: TagId
  GaddrT*: TagId
  TaddrT*: TagId
  NotT*: TagId
  NegT*: TagId
  AddscaledT*: TagId
  AddT*: TagId
  SubT*: TagId
  MulT*: TagId
  DivT*: TagId
  ModT*: TagId
  ShrT*: TagId
  ShlT*: TagId
  BitandT*: TagId
  BitorT*: TagId
  BitnotT*: TagId
  BitxorT*: TagId
  EqT*: TagId
  NeqT*: TagId
  LeT*: TagId
  LtT*: TagId
  SextT*: TagId
  ZextT*: TagId
  FextT*: TagId
  FnarrowT*: TagId
  TruncT*: TagId
  FtoiT*: TagId
  FtouT*: TagId
  ItofT*: TagId
  UtofT*: TagId
  VarT*: TagId
  GvarT*: TagId
  TvarT*: TagId
  ValuesT*: TagId
  ConstT*: TagId
  AsciizT*: TagId
  EmitT*: TagId
  AsgnT*: TagId
  StoreT*: TagId
  LabT*: TagId
  LoopT*: TagId
  TjmpT*: TagId
  FjmpT*: TagId
  JmpT*: TagId
  JloopT*: TagId
  RetT*: TagId
  StmtsT*: TagId
  ParamT*: TagId
  ParamsT*: TagId
  ProcT*: TagId
  CdeclT*: TagId
  StdcallT*: TagId
  SafecallT*: TagId
  SyscallT*: TagId
  FastcallT*: TagId
  ThiscallT*: TagId
  NoconvT*: TagId
  MemberT*: TagId
  AttrT*: TagId
  WasT*: TagId
  SelectanyT*: TagId
  PragmasT*: TagId
  AlignT*: TagId
  ImpT*: TagId
  InclT*: TagId

proc registerTags*() =
  IT = registerTag "i"
  UT = registerTag "u"
  FT = registerTag "f"
  MT = registerTag "m"
  BT = registerTag "b"
  LoadT = registerTag "load"
  CallT = registerTag "call"
  VarargsT = registerTag "varargs"
  VaddrT = registerTag "vaddr"
  GaddrT = registerTag "gaddr"
  TaddrT = registerTag "taddr"
  NotT = registerTag "not"
  NegT = registerTag "neg"
  AddscaledT = registerTag "addscaled"
  AddT = registerTag "add"
  SubT = registerTag "sub"
  MulT = registerTag "mul"
  DivT = registerTag "div"
  ModT = registerTag "mod"
  ShrT = registerTag "shr"
  ShlT = registerTag "shl"
  BitandT = registerTag "bitand"
  BitorT = registerTag "bitor"
  BitnotT = registerTag "bitnot"
  BitxorT = registerTag "bitxor"
  EqT = registerTag "eq"
  NeqT = registerTag "neq"
  LeT = registerTag "le"
  LtT = registerTag "lt"
  SextT = registerTag "sext"
  ZextT = registerTag "zext"
  FextT = registerTag "fext"
  FnarrowT = registerTag "fnarrow"
  TruncT = registerTag "trunc"
  FtoiT = registerTag "ftoi"
  FtouT = registerTag "ftou"
  ItofT = registerTag "itof"
  UtofT = registerTag "utof"
  VarT = registerTag "var"
  GvarT = registerTag "gvar"
  TvarT = registerTag "tvar"
  ValuesT = registerTag "values"
  ConstT = registerTag "const"
  AsciizT = registerTag "asciiz"
  EmitT = registerTag "emit"
  AsgnT = registerTag "asgn"
  StoreT = registerTag "store"
  LabT = registerTag "lab"
  LoopT = registerTag "loop"
  TjmpT = registerTag "tjmp"
  FjmpT = registerTag "fjmp"
  JmpT = registerTag "jmp"
  JloopT = registerTag "jloop"
  RetT = registerTag "ret"
  StmtsT = registerTag "stmts"
  ParamT = registerTag "param"
  ParamsT = registerTag "params"
  ProcT = registerTag "proc"
  CdeclT = registerTag "cdecl"
  StdcallT = registerTag "stdcall"
  SafecallT = registerTag "safecall"
  SyscallT = registerTag "syscall"
  FastcallT = registerTag "fastcall"
  ThiscallT = registerTag "thiscall"
  NoconvT = registerTag "noconv"
  MemberT = registerTag "member"
  AttrT = registerTag "attr"
  WasT = registerTag "was"
  SelectanyT = registerTag "selectany"
  PragmasT = registerTag "pragmas"
  AlignT = registerTag "align"
  ImpT = registerTag "imp"
  InclT = registerTag "incl"
