# GENERATED BY NifGram. DO NOT EDIT!
# ORIGINAL FILE: ./src/nifc/amd64/asm_grammar.nif
import nifstreams

var
  GlobalT*: TagId
  TextT*: TagId
  ExternT*: TagId
  TimesT*: TagId
  StringT*: TagId
  ByteT*: TagId
  WordT*: TagId
  LongT*: TagId
  QuadT*: TagId
  DataT*: TagId
  RodataT*: TagId
  StmtsT*: TagId
  RaxT*: TagId
  RbxT*: TagId
  RcxT*: TagId
  RdxT*: TagId
  RsiT*: TagId
  RdiT*: TagId
  RbpT*: TagId
  RspT*: TagId
  R8T*: TagId
  R9T*: TagId
  R10T*: TagId
  R11T*: TagId
  R12T*: TagId
  R13T*: TagId
  R14T*: TagId
  R15T*: TagId
  Rsp2T*: TagId
  Xmm0T*: TagId
  Xmm1T*: TagId
  Xmm2T*: TagId
  Xmm3T*: TagId
  Xmm4T*: TagId
  Xmm6T*: TagId
  Xmm7T*: TagId
  Xmm8T*: TagId
  Xmm9T*: TagId
  Xmm10T*: TagId
  Xmm11T*: TagId
  Xmm12T*: TagId
  Xmm13T*: TagId
  Xmm14T*: TagId
  Xmm15T*: TagId
  RelT*: TagId
  FsT*: TagId
  Mem1T*: TagId
  Mem2T*: TagId
  Mem3T*: TagId
  Mem4T*: TagId
  ByteatT*: TagId
  WordatT*: TagId
  MovT*: TagId
  MovapdT*: TagId
  MovsdT*: TagId
  LeaT*: TagId
  AddT*: TagId
  SubT*: TagId
  MulT*: TagId
  ImulT*: TagId
  DivT*: TagId
  IdivT*: TagId
  XorT*: TagId
  OrT*: TagId
  AndT*: TagId
  ShlT*: TagId
  ShrT*: TagId
  SalT*: TagId
  SarT*: TagId
  AddsdT*: TagId
  SubsdT*: TagId
  MulsdT*: TagId
  DivsdT*: TagId
  PushT*: TagId
  PopT*: TagId
  IncT*: TagId
  DecT*: TagId
  NegT*: TagId
  NotT*: TagId
  CmpT*: TagId
  TestT*: TagId
  CallT*: TagId
  LabT*: TagId
  LooplabT*: TagId
  SeteT*: TagId
  SetaT*: TagId
  SetaeT*: TagId
  SetbT*: TagId
  SetbeT*: TagId
  SetgT*: TagId
  SetgeT*: TagId
  SetlT*: TagId
  SetleT*: TagId
  SetzT*: TagId
  SetcT*: TagId
  SetoT*: TagId
  SetsT*: TagId
  SetpT*: TagId
  SetneT*: TagId
  SetnaT*: TagId
  SetnaeT*: TagId
  SetnbT*: TagId
  SetnbeT*: TagId
  SetngT*: TagId
  SetngeT*: TagId
  SetnlT*: TagId
  SetnleT*: TagId
  SetnzT*: TagId
  JmpT*: TagId
  JloopT*: TagId
  JeT*: TagId
  JneT*: TagId
  JzT*: TagId
  JnzT*: TagId
  JgT*: TagId
  JngT*: TagId
  JgeT*: TagId
  JngeT*: TagId
  JaT*: TagId
  JnaT*: TagId
  JaeT*: TagId
  JnaeT*: TagId
  NopT*: TagId
  SkipT*: TagId
  RetT*: TagId
  SyscallT*: TagId
  CommentT*: TagId

proc registerTags*() =
  GlobalT = registerTag "global"
  TextT = registerTag "text"
  ExternT = registerTag "extern"
  TimesT = registerTag "times"
  StringT = registerTag "string"
  ByteT = registerTag "byte"
  WordT = registerTag "word"
  LongT = registerTag "long"
  QuadT = registerTag "quad"
  DataT = registerTag "data"
  RodataT = registerTag "rodata"
  StmtsT = registerTag "stmts"
  RaxT = registerTag "rax"
  RbxT = registerTag "rbx"
  RcxT = registerTag "rcx"
  RdxT = registerTag "rdx"
  RsiT = registerTag "rsi"
  RdiT = registerTag "rdi"
  RbpT = registerTag "rbp"
  RspT = registerTag "rsp"
  R8T = registerTag "r8"
  R9T = registerTag "r9"
  R10T = registerTag "r10"
  R11T = registerTag "r11"
  R12T = registerTag "r12"
  R13T = registerTag "r13"
  R14T = registerTag "r14"
  R15T = registerTag "r15"
  Rsp2T = registerTag "rsp2"
  Xmm0T = registerTag "xmm0"
  Xmm1T = registerTag "xmm1"
  Xmm2T = registerTag "xmm2"
  Xmm3T = registerTag "xmm3"
  Xmm4T = registerTag "xmm4"
  Xmm6T = registerTag "xmm6"
  Xmm7T = registerTag "xmm7"
  Xmm8T = registerTag "xmm8"
  Xmm9T = registerTag "xmm9"
  Xmm10T = registerTag "xmm10"
  Xmm11T = registerTag "xmm11"
  Xmm12T = registerTag "xmm12"
  Xmm13T = registerTag "xmm13"
  Xmm14T = registerTag "xmm14"
  Xmm15T = registerTag "xmm15"
  RelT = registerTag "rel"
  FsT = registerTag "fs"
  Mem1T = registerTag "mem1"
  Mem2T = registerTag "mem2"
  Mem3T = registerTag "mem3"
  Mem4T = registerTag "mem4"
  ByteatT = registerTag "byteat"
  WordatT = registerTag "wordat"
  MovT = registerTag "mov"
  MovapdT = registerTag "movapd"
  MovsdT = registerTag "movsd"
  LeaT = registerTag "lea"
  AddT = registerTag "add"
  SubT = registerTag "sub"
  MulT = registerTag "mul"
  ImulT = registerTag "imul"
  DivT = registerTag "div"
  IdivT = registerTag "idiv"
  XorT = registerTag "xor"
  OrT = registerTag "or"
  AndT = registerTag "and"
  ShlT = registerTag "shl"
  ShrT = registerTag "shr"
  SalT = registerTag "sal"
  SarT = registerTag "sar"
  AddsdT = registerTag "addsd"
  SubsdT = registerTag "subsd"
  MulsdT = registerTag "mulsd"
  DivsdT = registerTag "divsd"
  PushT = registerTag "push"
  PopT = registerTag "pop"
  IncT = registerTag "inc"
  DecT = registerTag "dec"
  NegT = registerTag "neg"
  NotT = registerTag "not"
  CmpT = registerTag "cmp"
  TestT = registerTag "test"
  CallT = registerTag "call"
  LabT = registerTag "lab"
  LooplabT = registerTag "looplab"
  SeteT = registerTag "sete"
  SetaT = registerTag "seta"
  SetaeT = registerTag "setae"
  SetbT = registerTag "setb"
  SetbeT = registerTag "setbe"
  SetgT = registerTag "setg"
  SetgeT = registerTag "setge"
  SetlT = registerTag "setl"
  SetleT = registerTag "setle"
  SetzT = registerTag "setz"
  SetcT = registerTag "setc"
  SetoT = registerTag "seto"
  SetsT = registerTag "sets"
  SetpT = registerTag "setp"
  SetneT = registerTag "setne"
  SetnaT = registerTag "setna"
  SetnaeT = registerTag "setnae"
  SetnbT = registerTag "setnb"
  SetnbeT = registerTag "setnbe"
  SetngT = registerTag "setng"
  SetngeT = registerTag "setnge"
  SetnlT = registerTag "setnl"
  SetnleT = registerTag "setnle"
  SetnzT = registerTag "setnz"
  JmpT = registerTag "jmp"
  JloopT = registerTag "jloop"
  JeT = registerTag "je"
  JneT = registerTag "jne"
  JzT = registerTag "jz"
  JnzT = registerTag "jnz"
  JgT = registerTag "jg"
  JngT = registerTag "jng"
  JgeT = registerTag "jge"
  JngeT = registerTag "jnge"
  JaT = registerTag "ja"
  JnaT = registerTag "jna"
  JaeT = registerTag "jae"
  JnaeT = registerTag "jnae"
  NopT = registerTag "nop"
  SkipT = registerTag "skip"
  RetT = registerTag "ret"
  SyscallT = registerTag "syscall"
  CommentT = registerTag "comment"
