# It supports overwriting tested results using `--overwrite`

import std / [os]
import "../src/lib" / [nifbuilder]

const
  ExpectedNifBuilderResult = """(.nif27)
(.vendor "tester")
(.dialect "niftest")
(stmts@4,5,mymodb.nim
 (call@1,3,mymod.nim foo.3.mymod 3423 50.4))"""

proc buildSomething(b: sink Builder): string =
  b.addHeader "tester", "niftest"
  b.withTree "stmts":
    b.addLineInfo 4, 5, "mymodb.nim"
    b.withTree "call":
      b.addLineInfo 1, 3, "mymod.nim"
      b.addSymbol "foo.3.mymod"
      b.addIntLit 3423
      b.addFloatLit 50.4

  assert(not b.attachedToFile)
  result = b.extract()

proc testNifBuilder() =
  var b = open(10)
  assert buildSomething(b) == ExpectedNifBuilderResult

testNifBuilder()

proc fatal(msg: string) = quit "FAILURE " & msg

proc exec(cmd: string) =
  if execShellCmd(cmd) != 0: fatal cmd

proc withExt(f, ext: string): string =
  result = f.changeFileExt(ext)
  if not fileExists(result):
    fatal "cannot find output file " & result

let overwrite = os.paramCount() > 0 and os.paramStr(1) == "--overwrite"

proc testNifGram(overwrite: bool) =
  exec "nim c src/nifgram/nifgram"
  var toRemove: seq[string] = @[]
  let f = "src/nifgram/examples/test_grammar.nif"
  exec ("src" / "nifgram" / "nifgram").addFileExt(ExeExt) & " " & f

  let r = f.withExt(".nim")
  let e = "tests/data/test_grammar.nim"
  if not os.sameFileContent(r, e):
    if overwrite:
      moveFile(r, e)
    else:
      fatal "files have not the same content: " & e & " " & r
  else:
    toRemove.add r
  for rem in toRemove:
    removeFile rem

testNifGram(overwrite)

proc checkGenTags() =
  # When you changed `doc/tags.md` but forgot to run `tools/gen_tags` and sent the pull request,
  # this proc detects that files in `src/models/*.nim` are not updated.

  const ModelsDir = "src" / "models"
  const OrigModelsDir = ModelsDir & "_orig"
  moveDir ModelsDir, OrigModelsDir
  createDir ModelsDir
  exec "nim c -r tools/gen_tags.nim"

  var err = ""
  for kind, path in walkDir(ModelsDir, true, true):
    if kind == pcFile:
      let orig = OrigModelsDir / path
      let generated = ModelsDir / path
      #echo "cmp ", orig, " and ", generated
      if not sameFileContent(orig, generated):
        err = generated & " doesn't match the file generated by `tools/gen_tags`. You probably changed `doc/tags.md` but didn't run `tools/gen_tags.nim`." &
              " Or you changed " & generated & " instead of `doc/tags.md` to add a new tag.\n" &
              "When you add or change tags, edit `doc/tags.md` and run `tools/gen_tags.nim` to update " & generated

  removeDir ModelsDir
  moveDir OrigModelsDir, ModelsDir

  if err != "":
    fatal err

checkGenTags()

proc hasturTests(overwrite: bool) =
  # CI sets NIMONY_CC=clang on Windows so tests exercise the clang-on-MinGW
  # path (faster cc step + native PE TLS). Locally the env var is unset
  # and the gcc default kicks in. On Windows + clang we also force LLD as
  # the linker: clang emits native PE TLS by default but ld.bfd lays out
  # `.tls$` incorrectly, producing binaries that segfault on first TLS
  # access; LLD's layout matches what the loader expects.
  var args = "--jobs:auto"
  let cc = os.getEnv("NIMONY_CC")
  if cc.len > 0:
    args.add " --forward:--cc:" & cc
    when defined(windows):
      if cc == "clang":
        args.add " --forward:--passL:-fuse-ld=lld"
  if overwrite:
    args.add " --overwrite"
  # GitHub Actions (and most CI) set `CI=true`. Release-built host tools
  # compile tests much faster with no coverage loss for regression runs.
  if os.getEnv("CI").len > 0:
    args = "--release " & args
  # Build hastur once into `bin/` as a dedicated step, then drive the suite
  # with the compiled binary. Previously `nim c -r src/hastur … all` fused
  # the compile and the run, so a hastur *compile* error surfaced as a bogus
  # test failure, and hastur's parallel runner re-exec'd itself via a
  # nimcache temp binary (`getAppFilename`) instead of a stable `bin/hastur`.
  # `--warningAsError:{ProveInit,Uninit}:off` mirrors hastur's own
  # `nimcPrefix`: `src/config.nims` promotes those to errors, which Nim
  # 2.2.10's `typedthreads` (`createThread`, used by the parallel runner)
  # trips.
  let hastur = ("bin" / "hastur").addFileExt(ExeExt)
  exec "nim c --warningAsError:ProveInit:off --warningAsError:Uninit:off " &
       "-o:" & hastur & " src/hastur"
  exec hastur & " " & args & " all"

hasturTests(overwrite)
