# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

import tags

type
  CallConv* = enum
    NoCallConv
    Cdecl = (ord(CdeclTagId), "cdecl")  ## `cdecl` calling convention
    Stdcall = (ord(StdcallTagId), "stdcall")  ## `stdcall` calling convention
    Safecall = (ord(SafecallTagId), "safecall")  ## `safecall` calling convention
    Syscall = (ord(SyscallTagId), "syscall")  ## `syscall` calling convention
    Fastcall = (ord(FastcallTagId), "fastcall")  ## `fastcall` calling convention
    Thiscall = (ord(ThiscallTagId), "thiscall")  ## `thiscall` calling convention
    Noconv = (ord(NoconvTagId), "noconv")  ## no explicit calling convention
    Member = (ord(MemberTagId), "member")  ## `member` calling convention
    Nimcall = (ord(NimcallTagId), "nimcall")  ## `nimcall` calling convention

proc rawTagIsCallConv*(raw: TagEnum): bool {.inline.} =
  raw >= CdeclTagId and raw <= NimcallTagId

