# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

const
  TagData* = [
    ("err", 1),
    ("suf", 2),
    ("at", 3),
    ("deref", 4),
    ("dot", 5),
    ("pat", 6),
    ("par", 7),
    ("addr", 8),
    ("nil", 9),
    ("inf", 10),
    ("neginf", 11),
    ("nan", 12),
    ("false", 13),
    ("true", 14),
    ("and", 15),
    ("or", 16),
    ("not", 17),
    ("neg", 18),
    ("sizeof", 19),
    ("alignof", 20),
    ("offsetof", 21),
    ("oconstr", 22),
    ("aconstr", 23),
    ("bracket", 24),
    ("curly", 25),
    ("curlyat", 26),
    ("kv", 27),
    ("vv", 28),
    ("add", 29),
    ("sub", 30),
    ("mul", 31),
    ("div", 32),
    ("mod", 33),
    ("shr", 34),
    ("shl", 35),
    ("bitand", 36),
    ("bitor", 37),
    ("bitxor", 38),
    ("bitnot", 39),
    ("eq", 40),
    ("neq", 41),
    ("le", 42),
    ("lt", 43),
    ("cast", 44),
    ("conv", 45),
    ("call", 46),
    ("cmd", 47),
    ("range", 48),
    ("ranges", 49),
    ("gvar", 50),
    ("tvar", 51),
    ("var", 52),
    ("param", 53),
    ("const", 54),
    ("result", 55),
    ("glet", 56),
    ("tlet", 57),
    ("let", 58),
    ("cursor", 59),
    ("typevar", 60),
    ("efld", 61),
    ("fld", 62),
    ("proc", 63),
    ("func", 64),
    ("iterator", 65),
    ("converter", 66),
    ("method", 67),
    ("macro", 68),
    ("template", 69),
    ("type", 70),
    ("block", 71),
    ("module", 72),
    ("cchoice", 73),
    ("ochoice", 74),
    ("emit", 75),
    ("asgn", 76),
    ("scope", 77),
    ("if", 78),
    ("when", 79),
    ("elif", 80),
    ("else", 81),
    ("typevars", 82),
    ("break", 83),
    ("continue", 84),
    ("for", 85),
    ("while", 86),
    ("case", 87),
    ("of", 88),
    ("lab", 89),
    ("jmp", 90),
    ("ret", 91),
    ("yld", 92),
    ("stmts", 93),
    ("params", 94),
    ("union", 95),
    ("object", 96),
    ("enum", 97),
    ("proctype", 98),
    ("atomic", 99),
    ("ro", 100),
    ("restrict", 101),
    ("cppref", 102),
    ("i", 103),
    ("u", 104),
    ("f", 105),
    ("c", 106),
    ("bool", 107),
    ("void", 108),
    ("ptr", 109),
    ("array", 110),
    ("flexarray", 111),
    ("aptr", 112),
    ("cdecl", 113),
    ("stdcall", 114),
    ("safecall", 115),
    ("syscall", 116),
    ("fastcall", 117),
    ("thiscall", 118),
    ("noconv", 119),
    ("member", 120),
    ("nimcall", 121),
    ("inline", 122),
    ("noinline", 123),
    ("attr", 124),
    ("varargs", 125),
    ("was", 126),
    ("selectany", 127),
    ("pragmas", 128),
    ("pragmax", 129),
    ("align", 130),
    ("bits", 131),
    ("vector", 132),
    ("imp", 133),
    ("nodecl", 134),
    ("incl", 135),
    ("excl", 136),
    ("include", 137),
    ("import", 138),
    ("importas", 139),
    ("from", 140),
    ("importexcept", 141),
    ("export", 142),
    ("exportexcept", 143),
    ("comment", 144),
    ("discard", 145),
    ("try", 146),
    ("raise", 147),
    ("onerr", 148),
    ("raises", 149),
    ("errs", 150),
    ("static", 151),
    ("ite", 152),
    ("graph", 153),
    ("forbind", 154),
    ("kill", 155),
    ("unpackflat", 156),
    ("unpacktup", 157),
    ("unpackdecl", 158),
    ("except", 159),
    ("fin", 160),
    ("refobj", 161),
    ("ptrobj", 162),
    ("tuple", 163),
    ("onum", 164),
    ("ref", 165),
    ("mut", 166),
    ("out", 167),
    ("lent", 168),
    ("sink", 169),
    ("nilt", 170),
    ("concept", 171),
    ("distinct", 172),
    ("itertype", 173),
    ("rangetype", 174),
    ("uarray", 175),
    ("openarray", 176),
    ("set", 177),
    ("auto", 178),
    ("symkind", 179),
    ("typekind", 180),
    ("typedesc", 181),
    ("untyped", 182),
    ("typed", 183),
    ("cstring", 184),
    ("pointer", 185),
    ("ordinal", 186),
    ("magic", 187),
    ("importc", 188),
    ("importcpp", 189),
    ("exportc", 190),
    ("header", 191),
    ("threadvar", 192),
    ("global", 193),
    ("discardable", 194),
    ("noreturn", 195),
    ("borrow", 196),
    ("noSideEffect", 197),
    ("nodestroy", 198),
    ("plugin", 199),
    ("bycopy", 200),
    ("byref", 201),
    ("noinit", 202),
    ("requires", 203),
    ("ensures", 204),
    ("build", 205),
    ("string", 206),
    ("quoted", 207),
    ("hderef", 208),
    ("ddot", 209),
    ("haddr", 210),
    ("newobj", 211),
    ("tup", 212),
    ("setconstr", 213),
    ("tabconstr", 214),
    ("ashr", 215),
    ("oconv", 216),
    ("hconv", 217),
    ("dconv", 218),
    ("callstrlit", 219),
    ("infix", 220),
    ("prefix", 221),
    ("hcall", 222),
    ("compiles", 223),
    ("declared", 224),
    ("defined", 225),
    ("high", 226),
    ("low", 227),
    ("typeof", 228),
    ("unpack", 229),
    ("enumtostr", 230),
    ("ismainmodule", 231),
    ("defaultobj", 232),
    ("defaulttup", 233),
    ("expr", 234),
    ("do", 235),
    ("arrat", 236),
    ("tupat", 237),
    ("plusset", 238),
    ("minusset", 239),
    ("mulset", 240),
    ("xorset", 241),
    ("eqset", 242),
    ("leset", 243),
    ("ltset", 244),
    ("inset", 245),
    ("card", 246),
    ("emove", 247),
    ("destroy", 248),
    ("dup", 249),
    ("copy", 250),
    ("wasmoved", 251),
    ("sinkh", 252),
    ("trace", 253),
    ("errv", 254),
    ("staticstmt", 255),
    ("bind", 256),
    ("mixin", 257),
    ("using", 258),
    ("asm", 259),
    ("defer", 260),
    ("index", 261),
    ("public", 262),
    ("private", 263),
    ("inject", 264),
    ("gensym", 265)
  ]
const
  ErrTagId* = 1
  SufTagId* = 2
  AtTagId* = 3
  DerefTagId* = 4
  DotTagId* = 5
  PatTagId* = 6
  ParTagId* = 7
  AddrTagId* = 8
  NilTagId* = 9
  InfTagId* = 10
  NeginfTagId* = 11
  NanTagId* = 12
  FalseTagId* = 13
  TrueTagId* = 14
  AndTagId* = 15
  OrTagId* = 16
  NotTagId* = 17
  NegTagId* = 18
  SizeofTagId* = 19
  AlignofTagId* = 20
  OffsetofTagId* = 21
  OconstrTagId* = 22
  AconstrTagId* = 23
  BracketTagId* = 24
  CurlyTagId* = 25
  CurlyatTagId* = 26
  KvTagId* = 27
  VvTagId* = 28
  AddTagId* = 29
  SubTagId* = 30
  MulTagId* = 31
  DivTagId* = 32
  ModTagId* = 33
  ShrTagId* = 34
  ShlTagId* = 35
  BitandTagId* = 36
  BitorTagId* = 37
  BitxorTagId* = 38
  BitnotTagId* = 39
  EqTagId* = 40
  NeqTagId* = 41
  LeTagId* = 42
  LtTagId* = 43
  CastTagId* = 44
  ConvTagId* = 45
  CallTagId* = 46
  CmdTagId* = 47
  RangeTagId* = 48
  RangesTagId* = 49
  GvarTagId* = 50
  TvarTagId* = 51
  VarTagId* = 52
  ParamTagId* = 53
  ConstTagId* = 54
  ResultTagId* = 55
  GletTagId* = 56
  TletTagId* = 57
  LetTagId* = 58
  CursorTagId* = 59
  TypevarTagId* = 60
  EfldTagId* = 61
  FldTagId* = 62
  ProcTagId* = 63
  FuncTagId* = 64
  IteratorTagId* = 65
  ConverterTagId* = 66
  MethodTagId* = 67
  MacroTagId* = 68
  TemplateTagId* = 69
  TypeTagId* = 70
  BlockTagId* = 71
  ModuleTagId* = 72
  CchoiceTagId* = 73
  OchoiceTagId* = 74
  EmitTagId* = 75
  AsgnTagId* = 76
  ScopeTagId* = 77
  IfTagId* = 78
  WhenTagId* = 79
  ElifTagId* = 80
  ElseTagId* = 81
  TypevarsTagId* = 82
  BreakTagId* = 83
  ContinueTagId* = 84
  ForTagId* = 85
  WhileTagId* = 86
  CaseTagId* = 87
  OfTagId* = 88
  LabTagId* = 89
  JmpTagId* = 90
  RetTagId* = 91
  YldTagId* = 92
  StmtsTagId* = 93
  ParamsTagId* = 94
  UnionTagId* = 95
  ObjectTagId* = 96
  EnumTagId* = 97
  ProctypeTagId* = 98
  AtomicTagId* = 99
  RoTagId* = 100
  RestrictTagId* = 101
  CpprefTagId* = 102
  ITagId* = 103
  UTagId* = 104
  FTagId* = 105
  CTagId* = 106
  BoolTagId* = 107
  VoidTagId* = 108
  PtrTagId* = 109
  ArrayTagId* = 110
  FlexarrayTagId* = 111
  AptrTagId* = 112
  CdeclTagId* = 113
  StdcallTagId* = 114
  SafecallTagId* = 115
  SyscallTagId* = 116
  FastcallTagId* = 117
  ThiscallTagId* = 118
  NoconvTagId* = 119
  MemberTagId* = 120
  NimcallTagId* = 121
  InlineTagId* = 122
  NoinlineTagId* = 123
  AttrTagId* = 124
  VarargsTagId* = 125
  WasTagId* = 126
  SelectanyTagId* = 127
  PragmasTagId* = 128
  PragmaxTagId* = 129
  AlignTagId* = 130
  BitsTagId* = 131
  VectorTagId* = 132
  ImpTagId* = 133
  NodeclTagId* = 134
  InclTagId* = 135
  ExclTagId* = 136
  IncludeTagId* = 137
  ImportTagId* = 138
  ImportasTagId* = 139
  FromTagId* = 140
  ImportexceptTagId* = 141
  ExportTagId* = 142
  ExportexceptTagId* = 143
  CommentTagId* = 144
  DiscardTagId* = 145
  TryTagId* = 146
  RaiseTagId* = 147
  OnerrTagId* = 148
  RaisesTagId* = 149
  ErrsTagId* = 150
  StaticTagId* = 151
  IteTagId* = 152
  GraphTagId* = 153
  ForbindTagId* = 154
  KillTagId* = 155
  UnpackflatTagId* = 156
  UnpacktupTagId* = 157
  UnpackdeclTagId* = 158
  ExceptTagId* = 159
  FinTagId* = 160
  RefobjTagId* = 161
  PtrobjTagId* = 162
  TupleTagId* = 163
  OnumTagId* = 164
  RefTagId* = 165
  MutTagId* = 166
  OutTagId* = 167
  LentTagId* = 168
  SinkTagId* = 169
  NiltTagId* = 170
  ConceptTagId* = 171
  DistinctTagId* = 172
  ItertypeTagId* = 173
  RangetypeTagId* = 174
  UarrayTagId* = 175
  OpenarrayTagId* = 176
  SetTagId* = 177
  AutoTagId* = 178
  SymkindTagId* = 179
  TypekindTagId* = 180
  TypedescTagId* = 181
  UntypedTagId* = 182
  TypedTagId* = 183
  CstringTagId* = 184
  PointerTagId* = 185
  OrdinalTagId* = 186
  MagicTagId* = 187
  ImportcTagId* = 188
  ImportcppTagId* = 189
  ExportcTagId* = 190
  HeaderTagId* = 191
  ThreadvarTagId* = 192
  GlobalTagId* = 193
  DiscardableTagId* = 194
  NoreturnTagId* = 195
  BorrowTagId* = 196
  NoSideEffectTagId* = 197
  NodestroyTagId* = 198
  PluginTagId* = 199
  BycopyTagId* = 200
  ByrefTagId* = 201
  NoinitTagId* = 202
  RequiresTagId* = 203
  EnsuresTagId* = 204
  BuildTagId* = 205
  StringTagId* = 206
  QuotedTagId* = 207
  HderefTagId* = 208
  DdotTagId* = 209
  HaddrTagId* = 210
  NewobjTagId* = 211
  TupTagId* = 212
  SetconstrTagId* = 213
  TabconstrTagId* = 214
  AshrTagId* = 215
  OconvTagId* = 216
  HconvTagId* = 217
  DconvTagId* = 218
  CallstrlitTagId* = 219
  InfixTagId* = 220
  PrefixTagId* = 221
  HcallTagId* = 222
  CompilesTagId* = 223
  DeclaredTagId* = 224
  DefinedTagId* = 225
  HighTagId* = 226
  LowTagId* = 227
  TypeofTagId* = 228
  UnpackTagId* = 229
  EnumtostrTagId* = 230
  IsmainmoduleTagId* = 231
  DefaultobjTagId* = 232
  DefaulttupTagId* = 233
  ExprTagId* = 234
  DoTagId* = 235
  ArratTagId* = 236
  TupatTagId* = 237
  PlussetTagId* = 238
  MinussetTagId* = 239
  MulsetTagId* = 240
  XorsetTagId* = 241
  EqsetTagId* = 242
  LesetTagId* = 243
  LtsetTagId* = 244
  InsetTagId* = 245
  CardTagId* = 246
  EmoveTagId* = 247
  DestroyTagId* = 248
  DupTagId* = 249
  CopyTagId* = 250
  WasmovedTagId* = 251
  SinkhTagId* = 252
  TraceTagId* = 253
  ErrvTagId* = 254
  StaticstmtTagId* = 255
  BindTagId* = 256
  MixinTagId* = 257
  UsingTagId* = 258
  AsmTagId* = 259
  DeferTagId* = 260
  IndexTagId* = 261
  PublicTagId* = 262
  PrivateTagId* = 263
  InjectTagId* = 264
  GensymTagId* = 265
